[project]
name = "gobots"
version = "0.1.0"
description = "The GoBots to Hugging Face's Transformers. A repository for exploring and understanding transformer architectures"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.10.1",
    "datasets>=4.0.0",
    "torch>=2.7.1",
    "torchao>=0.12.0",
    "torchtune>=0.6.1",
    "trackio>=0.3.4",
    "transformers>=4.54.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.5",
]
