[project]
name = "gobots"
version = "0.1.0"
description = "The GoBots to Hugging Face's Transformers. A repository for exploring and understanding transformer architectures"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.10.1",
    "boto3>=1.40.54",
    "datasets>=4.2.0",
    "huggingface-hub>=0.35.3",
    "smart-open>=7.3.1",
    "torch==2.8.0",
    "torchao==0.13.0",
    "torchtune>=0.6.1",
    "trackio>=0.6.0",
    "transformers>=4.57.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
]
